### ISSUE TITLE
I get a problem when traing the model

### ISSUE THREAD

**Issue by wangdalin** [rulin-jone/Image-manipulation-detection#3]
the error info is " Allocation of XXXXXXXX exceeds 10% of system memory" , I run the code on a  64GB memory  server with 12GB memory GPU, I want to know whether my server's memory is big enough to run the code ,or just I run it in a wrong way

**Comment by rulin-jone** [comment]
sorry, i just see your problem. your server's memory is big enough to run the code. Maybe you don't have a folder path to save the training model, or there is not enough space left on the hard disk.

**Comment by wangdalin** [comment]
I have finished my problem by using another mechine, but still thank you~
